plugins:
  pmd:
    enabled: true
  duplication:
    enabled: false
  structure:
    enabled: false
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "script/"
- "dev-utils/"
- "**/test/"
- "**/*.js"
- "**/*.css"
- "**/resources/"
- "**/lib/"
- "**/*.xml"
- "**/*.properties"
- "RestAdvertisementController.java"
- "RemittanceServiceImpl.java"
- "UpdateAssessmentController.java"
- "SewerageChargeCalculationService.java"
- "ValidationUtil.java"
